### ISSUE TITLE
missing eslint configuration

### ISSUE THREAD

**Issue by jay-jlm** [esausilva/example-create-react-app-express#17]
Getting the  following error on VS Code

```
Failed to load the ESLint library for the document /Users/[username]/projects/example-create-react-app-express/engine.js
To use ESLint please install eslint by running npm install eslint in the workspace folder example-create-react-app-express
```

I suppose this project relies on a global Eslint installation? 
If so maybe I'd suggest migrating to a local configuration, since global dependencies are no longer the recommend way to use JS dependencies, unless in very specific cases.

**Comment by esausilva** [comment]
@jay-jlm I do not have ESlint set up locally or globally. And I do not recognize that `engine.js` file, it is not part of the original project

**Comment by jay-jlm** [comment]
Yes, `engine.js` is just a file that I created was editing, but any file will get the same error.
