### ISSUE TITLE
React app client port 5000

### ISSUE THREAD

**Issue by Hienphamthe** [esausilva/example-create-react-app-express#3]
Hi, thank you for this tutorial.
However, I dont know why my react client starts at port 5000, which is supposed to be the port for express backend. Could you let me know how to fix this. Thanks.

**Comment by esausilva** [comment]
That is really strange. Without looking at your code it would be pretty difficult to research. If you are still having this issue, could you upload the code to GitHub? And I could take a look

**Comment by Hienphamthe** [comment]
I am sorry. That is my false. I follow some other instruction to set port as global. So both client and server start at this port.
