### ISSUE TITLE
heroku is not running my backend 

### ISSUE THREAD

**Issue by niksseif** [esausilva/example-create-react-app-express#4]
Here is my package json in the serverside
`{
    "name": "tidy-sum",
    "version": "1.0.0",
    "scripts": {
        "client": "cd client && yarn start",
        "server": "nodemon server.js",
        "dev": "concurrently --kill-others-on-fail \"yarn server\" \"yarn client\"",
        "start": "node server.js",
        "heroku-postbuild": "cd client && npm install && npm install --only=dev --no-shrinkwrap && npm run build"
    },
    "dependencies": {
        "body-parser": "^1.18.3",
        "cors": "^2.8.5",
        "express": "^4.16.4",
        "knex": "^0.16.3",
        "morgan": "^1.9.1",
        "pg": "^7.8.0"
    },
    "devDependencies": {
        "concurrently": "^4.0.1"
    }
}`

**Comment by WhiteJacket** [comment]
fixed?

**Comment by esausilva** [comment]
@niksseif are you still having this issue? if so, Express is not running? can you share the Heroku logs?
