### ISSUE TITLE
Backend not working properly post-production

### ISSUE THREAD

**Issue by andrew-levy** [esausilva/example-create-react-app-express#5]
After deploying my app on Heroku, I get the following error: 
`GET https://weetweet.herokuapp.com/api/hello 503 (Service Unavailable)`

My locally hosted app (which works perfectly) is running on localhost:3000 and the express server is running on localhost:5000. I set up the proxy as you did 

`{ "proxy": "http://localhost:5000/" }`
and the fetch call like this `fetch('/api/hello')` and `fetch('/api/posts')` (i switched world to posts)

Should I be doing something else so that Heroku can serve the backend somewhere? 

Here is my code: https://github.com/andrew-levy/Twitter-React-Express
Here is the web app: https://weetweet.herokuapp.com/

p.s. Thanks for the code boilerplate and the article guiding me through the process!

**Comment by esausilva** [comment]
Hi Andrew, I was looking at your code and noticed you are missing the module `twit`. 

In your `server.js` file line 12 you have `var Twit = require('twit')`, however that package is not installed. Running `yarn add twit` under the root directory should fix it.

**Comment by andrew-levy** [comment]
Hahaha of course it's something small like that. It works now, thanks for taking the time to look. First react-express project down, plenty more to come.

**Comment by esausilva** [comment]
Awesome! Keep it up 👍
