### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jsampayoramos** [esausilva/example-create-react-app-express#6]
Hi esausilva,
Thanks for sharing the app. It was very useful to get me started with react/express.
I would like to ask you how I could deploy manually the files to a server. Which files and folders do I have to place on the server and what needs to be the file structure.
Thanks

**Comment by esausilva** [comment]
Are you going to serve with Node? Apache? other server tech?

**Comment by jsampayoramos** [comment]
I am going to serve it with Node. I am using create react app.

**Comment by esausilva** [comment]
CRA creates a `build` folder. Copy that folder to your server and point your Node app to server that folder.

If you look at my Node server in Line 25 you can see how I'm doing it. You will also need lines 28-30 to redirect all requests back to React (https://github.com/esausilva/example-create-react-app-express/blob/master/server.js#L25-L30)

**Comment by jsampayoramos** [comment]
Thanks.
If I understand correctly you are serving the client/build folder in the
server. What if I were to past the files in the build folder created by CRA
directly on the top directory of the server. How would that impact line 25
and 29.

**Comment by esausilva** [comment]
That is correct. I am serving the `client/build` folder.

You mean file structure like below?
```
|-server.js
|-static/
|---css/
|---js/
|--...
|-index.html
|-...
```

Then you would have the following
```
...
app.use(express.static(__dirname);
app.get('*', function(req, res) {
  res.sendFile(path.join(__dirname, 'index.html'));
});
```

**Comment by jsampayoramos** [comment]
Thanks a lot :)

**Comment by esausilva** [comment]
You are welcome
